### ISSUE TITLE
cpp_source does not work

### ISSUE THREAD

**Issue by waynelapierre** [r-lib/cpp11#125]
I tried to use the cpp_source to source an example C++ function into R but got the error message:

```
Error in dyn.load(shared_lib, local = TRUE, now = TRUE) : 
  unable to load shared object '/tmp/RtmpGrs3dk/file228a974141e9d/src/cpp11.so':
  /tmp/RtmpGrs3dk/file228a974141e9d/src/cpp11.so: cannot open shared object file: No such file or directory
```

The example C++ function is 

```
double mean_cpp(doubles x) {
  int n = x.size();
  double total = 0;
  for(double value : x) {
    total += value;
  }
  return total / n;
}
```

When I put it into cpp_function, it worked. I have worked with Rcpp before but have never encountered such issue.

**Comment by jimhester** [comment]
The problem is your code failed to compile, because `cpp_source()` does not add the extra include and using declarations needed. But we were not throwing an error if the shared library did not build.

If you use `quiet = FALSE` you will see the error message that explains the problem, e.g. this is the fix for your example. `cpp_function()` worked because it adds the first three lines for you.

cpp11::cpp_source(code = '
  #include "cpp11/doubles.hpp"
  using namespace cpp11;

  [[cpp11::register]]
  double mean_cpp(doubles x) {
  int n = x.size();
  double total = 0;
  for(double value : x) {
    total += value;
  }
  return total / n;
}')

We now throw an error if the shared library fails to compile, so this should no longer be so confusing in the future.
