### ISSUE TITLE
Cannot use use std::vector

### ISSUE THREAD

**Issue by waynelapierre** [r-lib/cpp11#138]
I noticed that when using std::vector with cpp11, my C++ file won't compile using the cpp_source function in R. Below is a simple example:

```
#include <vector>
#include <cpp11.hpp>
using namespace std;
using namespace cpp11;

[[cpp11::register]]
double pv(vector<double> cf_amount, double r)
{
  auto res = 0.0;
  for (size_t t = 0; t < cf_amount.size(); ++t) 
  {
    res += cf_amount[t]/pow(1 + r, t + 1);
  }
  return res;
}

```

**Comment by jimhester** [comment]
You need to fully qualify it when used as an argument for the wrapping code to work.

e.g. `std::vector`.

The compilation is failing due to this error message.

```
/private/var/folders/9x/_8jnmxwj3rq1t90mlr6_0k1w0000gn/T/RtmpdMsZDw/filec3eb
31577b3c/src/cpp11.cpp:4:11: error: no template named 'vector'; did you mean
 'std::vector'?
double pv(vector<double> cf_amount, double r);
          ^~~~~~
          std::vector
```

``` r
writeLines("
#include <cpp11.hpp>
#include <vector>

using namespace cpp11;

[[cpp11::register]] double pv(std::vector<double> cf_amount, double r) {
  auto res = 0.0;
  for (size_t t = 0; t < cf_amount.size(); ++t) {
    res += cf_amount[t] / pow(1 + r, t + 1);
  }
  return res;
}
", "test.cpp")
cpp11::cpp_source("test.cpp")
```

<sup>Created on 2020-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In the general case when using custom types in function signatures you need to include any needed headers in a `pkgname_types.h` file. This is only possible in a formal R package, the `cpp_source()` functions do not support this.
