### ISSUE TITLE
Most recent function is faster

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/cpp11#14]
I was doing some benchmarking and got some strange results.

I think I got it minimal enough now. It appears that any function when being defined adds calling time to any previous functions.

``` r
library(cpp11)

cpp_function("void void_a() {}")
cpp_function("void void_b() {}")

bm <- bench::mark(
  void_a(),
  void_b()
)

plot(bm)
#> Loading required namespace: tidyr
```

![](https://i.imgur.com/f9IbfOd.png)

``` r

cpp_function("void void_b() {}")
cpp_function("void void_a() {}")

bm <- bench::mark(
  void_a(),
  void_b()
)

plot(bm)
```

![](https://i.imgur.com/upCHj0L.png)

<sup>Created on 2020-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
library(cpp11)

cpp_function("void void_a() {}")
cpp_function("void void_b() {}")
cpp_function("void void_c() {}")
cpp_function("void void_d() {}")
cpp_function("void void_e() {}")

bm <- bench::mark(
  void_a(),
  void_b(),
  void_c(),
  void_d(),
  void_e()
)

plot(bm)
#> Loading required namespace: tidyr
```

![](https://i.imgur.com/nMe8s85.png)

<sup>Created on 2020-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Thanks! The issue was we were previously not using the `PACKAGE` argument to `.Call()`, so each time you called `cpp_function()` an additional shared library was added to the search path and would have to be searched to find the function definition.

We now generate a (more) unique package name each time `source_cpp()` is called and use the `PACKAGE` argument, which ensures we have the same performance for all of the functions.

``` r
library(cpp11)
cpp_function("void void_a() {}")
cpp_function("void void_b() {}")
cpp_function("void void_c() {}")
cpp_function("void void_d() {}")
cpp_function("void void_e() {}")

bm <- bench::mark(
  void_a(),
  void_b(),
  void_c(),
  void_d(),
  void_e()
)

plot(bm)
#> Loading required namespace: tidyr
```

![](https://i.imgur.com/sFfHqZS.png)

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
Is it worth using a symbol in `.Call()` rather than a string? WRE claims it is _slightly_ faster to do so vs using a string + PACKAGE. It might not matter too much
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Speed-considerations
