### ISSUE TITLE
cannot use C++ std namespace for vector

### ISSUE THREAD

**Issue by waynelapierre** [r-lib/cpp11#163]
I noticed that even when I have used the C++ std namespace, I still need to type std::vector in my C++ file to make cpp_source work. Not sure if this is a bug.

**Comment by jimhester** [comment]
types use in function definitions that are decorated with `[[cpp11::register]]` need to be fully qualified, because any namespace definition you have in the file will not be in the registration file generated by cpp11. However type names within those functions will work as you would expect.

# This won't work because the return type is not fully qualified
```r
cpp11::cpp_source(code = '#include <cpp11.hpp>\n#include <string>

using namespace std;

[[cpp11::register]]
string foobar() {
  return string("foo") + "-bar";
}
')

# However this will
cpp11::cpp_source(code = '#include <cpp11.hpp>\n#include <string>

using namespace std;

[[cpp11::register]]
std::string foobar() {
  return string("foo") + "-bar";
}
')
```

**Comment by sbearrows** [comment]
Added to the FAQ page
